//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TelefonicaEntities : DbContext
{
    public TelefonicaEntities()
        : base("name=TelefonicaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Llamada> Llamadas { get; set; }
    public virtual DbSet<Telefono> Telefonos { get; set; }
    public virtual DbSet<Usuario> Usuarios { get; set; }
}
