//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Usuario
{
    public System.Guid UsuarioId { get; set; }
    public System.Guid TelefonoId { get; set; }
    public string Nombre { get; set; }

    public virtual Telefono Telefono { get; set; }
}
