//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telefonica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llamada
    {
        public System.Guid LlamadaId { get; set; }
        public System.Guid UsuarioId { get; set; }
        public System.Guid TelefonoId { get; set; }
        public System.DateTime InicioLlamada { get; set; }
        public System.DateTime FinLlamada { get; set; }
    
        public virtual Telefono Telefono { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
